### ISSUE TITLE
[Bug]: Puppeteer recognizes path parameters in FastAPI routes as f-strigns

### ISSUE THREAD

**Issue by Popkornium18** [chrisgrieser/nvim-puppeteer#10]
### Bug Description

When creating FastAPI routes you often write strings that look a lot like f-strings but should not be turned into f-strings automatically. See here for an example: [https://fastapi.tiangolo.com/tutorial/path-params/](https://fastapi.tiangolo.com/tutorial/path-params/)

puppeteer turns these strings into f-strings and requires workarounds to remove the f-string

### neovim version

```Text
latest
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
I don't feel confident fixing this, since I have no experience with FastAPI and therefore am not familiar with any potential edge cases. Should be sth via PR with someone who has actual experience with Fast API.

---

Just a general word of advice for when you create issues on GitHub
1. Don't post something like `version: latest`. It's unclear whether it's the latest nightly or stable, and especially if the issue is read some time later, it is not clear what the latest issue was at that time. Running `nvim --version` in the terminal really is not much work.
2. The "to reproduce" field is there for a reason. Post clear examples how an undesired operation looks like. Off-loading the research work how an API someone is not familiar with looks like makes it harder for anyone to work on that issue, reducing the likelihood that the issue is going to be addressed.

It's just a minor annoyance for me, so no big deal, but in bigger repos where a lot of issues are submitted, the chances are high that your issues will be closed without comment by the maintainers
