### ISSUE TITLE
[Bug]: does nothing?

### ISSUE THREAD

**Issue by ghost** [chrisgrieser/nvim-puppeteer#18]
### Bug Description

Can't get the plugin to work, like, at all. Even tried explicitly enabling it by calling `:PuppeteerEnable`. Tried in both JS and Python, new strings, existing strings, nothing works.

### To Reproduce

1. Install the plugin using lazy.nvim:
    ```
    {
      'chrisgrieser/nvim-puppeteer',
      lazy = false,
    },
    ```
2. Expect it to work.

### neovim version

```Text
NVIM v0.9.4
Build type: RelWithDebInfo
LuaJIT 2.1.1692716794
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/kwyntes/bouw/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/kwyntes/bouw/neovim/.deps/usr/include -I/home/kwyntes/bouw/neovim/build/src/nvim/auto -I/home/kwyntes/bouw/neovim/build/include -I/home/kwyntes/bouw/neovim/build/cmake.config -I/home/kwyntes/bouw/neovim/src -I/usr/include -I/home/kwyntes/bouw/neovim/.deps/usr/include -I/home/kwyntes/bouw/neovim/.deps/usr/include -I/home/kwyntes/bouw/neovim/.deps/usr/include -I/home/kwyntes/bouw/neovim/.deps/usr/include -I/home/kwyntes/bouw/neovim/.deps/usr/include -I/home/kwyntes/bouw/neovim/.deps/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
Do you have the treesitter parsers for the respective filetypes installed? Have you run `:TSUpdate` so you are on the latest parser versions?

If so, please provide an example code where the conversion is not working

**Comment by ghost** [comment]
Yep, I've installed the parsers for both JS and Python. Not sure what kind of example code you'd like to see, opening an empty file and typing a string doesn't work either - I doubt it depends on the code around it.

**Comment by chrisgrieser** [comment]
> Not sure what kind of example code you'd like to see, opening an empty file and typing a string doesn't work either

"typing a string" may be clear for you, but it is not unambiguous. Is it a value assigned to a variable? Is it a bare string? is it a multi-line string? Without you being a bit more specific, there is really nothing I can do, since it works fine on my end with every example I tried.

Also, I'd try a minimal config, i.e. a config with just nvim-puppeteer and lazy.nvim, in case it is another plugin interfering somehow.

Also, just in case: have you updated to the latest commit? there was a bug two weeks ago, that prevented the plugin from working.

**Comment by ghost** [comment]
> Is it a value assigned to a variable?

Yes.

> Is it a bare string?

Yes.

> is it a multi-line string?

Yes.

> Also, I'd try a minimal config, i.e. a config with just nvim-puppeteer and lazy.nvim, in case it is another plugin interfering somehow.

Still nothing. Tried a complete clean install with just lazy.nvim, nvim-treesitter and nvim-puppeteer.

> Also, just in case: have you updated to the latest commit? there was a bug two weeks ago, that prevented the plugin from working.

I installed the plugin yesterday so I should be on the latest version.

I realise that this issue might not get us anywhere like this, but I really have no idea how I should debug this. Interestingly enough, the plugin [axelvc/template-string.nvim](https://github.com/axelvc/template-string.nvim) (which essentially does the same thing as this plugin does) I also couldn't get to work, but I'm not sure what conclusion I should draw from that.

**Comment by chrisgrieser** [comment]
okay, I took a closer look and found a weird situation where treesitter does not update the AST in time. Might be a treesitter bug, dunno. In any case, should be fixed now.

---

> Yes. Yes. Yes.

Just a word of advice: you would save others (as well as yourself) some time, if you just provided some example code upfront, making questions like this unnecessary. That's what "to reproduce" sections in bug report forms are meant for

**Comment by ghost** [comment]
Sorry, I realise I sounded a bit passive-aggressive, which was not my intention, so my apologies.

I updated to the latest version, and I got it to work in one case.

If I open an empty JS file (`nvim file.js`) and type
```
let s = "${a}"<ESC>
```
it turns into a template string (note it only happens after I hit Escape, I'm not sure if that's the intended behaviour).

If I then backspace everything, and retype the same thing (and hit escape again), nothing happens.  
Also, if I remove the `$` or `{` or `}`, the string doesn't turn back into a normal string. So perhaps the plugin crashes after the first conversion?

Note that the conversion only happens when I still have my cursor somewhere in string when I hit escape, if I add a semicolon at the end for example, and then hit escape, nothing happens again (and subsequent attempts to reproduce the conversion using the same expression fail as well).

If, after I type `let s = "${a}"<ESC>` in a fresh file (and it gets converted), I hit `a` and type `;<CR>let t = "${b}"<ESC>`, something interesting happens again: only the last quotation mark turns into a backtick, and the first one (the opening `"`) doesn't.

I'm still really confused as to what might cause this, so I hope this info helps explain the issue a bit better.

**Comment by chrisgrieser** [comment]
> it only happens after I hit Escape, I'm not sure if that's the intended behaviour.

yes, that is intentional – otherwise, the plugin would have to monitor every single keystroke you do in insert mode which unnecessarily uses resources. Also, it would get in the way of typing when changes happen as soon as you type them. So the plugin triggers when you leave insert mode.

> Note that the conversion only happens when I still have my cursor somewhere in string when I hit escape, if I add a semicolon at the end for example, and then hit escape, nothing happens again

Yes, this is somewhat of a restriction, since the plugin only scans the node the cursor is at. To catch your described case, the plugin would, strictly speaking, have to scan the whole file, which again, would consume way more resources, which this edge case does not justify. (I never type any semicolons, since I let the formatter do that for me, which solves the problem for me.)

---

> If I then backspace everything, and retype the same thing (and hit escape again), nothing happens. Also, if I remove the $ or { or }, the string doesn't turn back into a normal string. So perhaps the plugin crashes after the first conversion?

Nope, if the plugin were to crash, you would get an error by nvim. That sounds like the issue I uncovered while looking into it earlier, namely treesitter not updating the AST in time. I am not sure though whether this is a treesitter bug, or intentional as a form of lazy-updating to save resources. I added a simple workaround for that in 9aa46b3, which fixed it in all cases I could find on my end. Not sure what case is left here 🤔 

What we can do is ensure we test under the same conditions. You should update to nvim 0.9.5. After that, could you try this minimal nvim config? It bootstraps lazy into your `/tmp/` folder together with treesitter and puppeteer. 

```lua
-- save as `minimal.lua`
local plugins = {
	{
		"nvim-treesitter/nvim-treesitter",
		build = ":TSUpdate",
		main = "nvim-treesitter.configs",
		opts = {
			ensure_installed = { "javascript" },
			highlight = { enable = true },
		},
	},
	{ "chrisgrieser/nvim-puppeteer" },
}
--------------------------------------------------------------------------------
for _, name in ipairs { "config", "data", "state", "cache" } do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = "/tmp/nvim-debug/" .. name
end
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	local lazyrepo = "https://github.com/folke/lazy.nvim"
	vim.fn.system { "git", "clone", "--filter=blob:none", lazyrepo, "--branch=stable", lazypath }
end
vim.opt.runtimepath:prepend(lazypath)
require("lazy").setup(plugins)
```

Then, run this:

```bash
nvim -u minimal.lua -- foobar.js
```

and see if the issue still occurs on your end.

**Comment by ghost** [comment]
Yep, that solves it! Thanks for helping!
