### ISSUE TITLE
Feature Request: mini.surround support

### ISSUE THREAD

**Issue by roobert** [chrisgrieser/nvim-puppeteer#2]
### Feature Requested

Great plugin!

I'd love to replace my usage of https://github.com/roobert/f-string-toggle.nvim

I have run up against one issue: when using `mini.surround` for deleting the brackets within a python f-string, (e.g: `gzd{`) the string state doesn't update.

I've tried to debug this by using `set verbose=9` to capture the potential `autocmd` that could be used as a hook, however, it's too verbose and I believe some kind of custom function may need making that involves filtering the output, etc. 

Opening this in case you know off-hand the correct autocmd to hook off to fix support, before I try and investigate further.

Thanks again for the plugin!

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
I use [nvim-surround](https://github.com/kylechui/nvim-surround) instead of `mini.surround`, and with that plugin, it works just fine though? 🤔 

nvim-puppeteer is triggered on `TextChanged`, so any kind of operation by another plugin should be picked up correctly. 

My guess is that this is `mini.surround` using `:noautocmd` somewhere in its code. That would be an issue you'd have to report at their issue, nothing I can do about it on this end, sorry

**Comment by roobert** [comment]
Interesting, it doesn't appear mini.surround (the default in lazyvim) is using `noautocmd`.

I've just tested with nvim-surround and having the same issue, will continue to investigate..

**Comment by chrisgrieser** [comment]
oh, when it's also occurring in nvim-surround, then it seems to be a different issue. Try in a minimal config with only surround and puppeteer as activated plugins maybe?

**Comment by chrisgrieser** [comment]
Closing this since probably not related to this plugin; please reply if there is still an issue!
