### ISSUE TITLE
[Bug]: using undo breaks puppeteer

### ISSUE THREAD

**Issue by Popkornium18** [chrisgrieser/nvim-puppeteer#8]
### Bug Description

Let's say we have this code: `print(f"These are the numbers: {' '.join([str(i) for i in [1, 2, 3]])}")`

We want to change the `' '.join` to `', '.join`. But we accidentally type `ci"`. Now we want to undo, hitting ESC, which causes puppeteer to remove the `f` but without actually making a change that nvim knows about. Then we hit `u`. Nvim reverts the undo, but the `f` is still missing from the string. We then try to fix it by prepending it, but puppeteer will remove it again. The only fix is to prepend `f ""` and then removing the space.

Neovim should know about the changes that puppeteer makes in order for this to work.

### neovim version

```Text
0.9.1
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
Actually, the opposite is the case: the removal of the `f` is registered as a change. So the undo does revert the removal, resulting in `f""`, which puppeteer then picks up on, so puppeteer removes the `f` again, since the string does not contain `{}`. 

It's a bit unfortunate, but an unlucky chain of things actually doing what they should. There are two simple workarounds for your specific situation:
1. Use bind `u` to `:noautocmd undo`, this will make vim ignore autocmds when you are undoing things.
2. Use `2u`, which does two undos, effectively restoring your original f-string. 

I am not sure how puppeteers behavior should be changed – excluding undos from triggering puppeteer (which I am not too sure how to do easily), would have other unintended side effects. One thing I can think of is to exclude empty strings from the auto-conversion.

**Comment by chrisgrieser** [comment]
Closing this, since I am not too sure how exactly puppeteers behavior could be changed other than excluding empty strings from triggering it

**Comment by chrisgrieser** [comment]
Never mind, I actually found a pretty simple solution to your problem, regardless of empty string or not. Is fixed.

**Comment by Popkornium18** [comment]
Works as expected. thanks.
